"""2025-05-13

Revision ID: 24250705fa6a
Revises: aa22aef3c15a
Create Date: 2025-05-13 11:53:33.432334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24250705fa6a'
down_revision: Union[str, None] = 'aa22aef3c15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labeling_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('correct_answer', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('case', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['knowledge_base.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labeling_data')
    # ### end Alembic commands ###
