"""2025-05-13

Revision ID: e128e019216c
Revises: 2bc7683f4ffb
Create Date: 2025-05-13 13:32:09.257575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e128e019216c'
down_revision: Union[str, None] = '2bc7683f4ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labeling_data', sa.Column('subject', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labeling_data', 'subject')
    # ### end Alembic commands ###
